### PR TITLE
Use protected methods in Query Providers

### PR DESCRIPTION
**Pull request by TomHAnderson**
When the DefaultOrm Query Provider is extended and the default createQuery function is not called, instead opting to run the filters directly, the functions to fetch the managers are private and cannot be accessed.

This PR changes any private functions on Query Providers to public.

### CODE REVIEW

**Comment by TomHAnderson** [comment]
This is not a BC but getting this approved during these holidays would be nice.

**Comment by TomHAnderson** [comment]
This approved PR is nearly 6 months old!  Is someone assigned to maintain this repository at zfcampus?  cc @webimpress @weierophinney

**Comment by webimpress** [comment]
@weierophinney What do you think? Can we release it safely as 1.5.2? Methods visibility is changed, for me it is not BC Break, because it will be the same if we add new `protected` methods.

**Comment by webimpress** [comment]
@TomHAnderson thanks !

**Pull request merged**
