### PR TITLE
Allow doctrine-module 2.1

### PR DESCRIPTION
**Pull request by shandyDev**
Related to #45 issue

### CODE REVIEW

**Comment by webimpress** [comment]
Thanks for PR. We need to have first `phpro/zf-doctrine-hydration-module` released with doctrine-module v2.1  compatibility. Please check the build here and you will see that these version are not even installed with the latest deps.

**Comment by thomasvargiu** [comment]
@webimpress can we merge this? `phpro/zf-doctrine-hydration-module` is now compatible

**Comment by webimpress** [comment]
@thomasvargiu, oh, thanks for the reminder, I'll work on it today!

**Comment by webimpress** [comment]
Thanks @shandyDev !

Released as 1.8.0!

**Pull request closed without merging**
