### PR TITLE
ZF3 component compatibility (follow-up to #31)

### PR DESCRIPTION
**Pull request by webimpress**
Follow-up to #31.

**TODO:**
- [x] Exposed to `zend-component-installer` as module (`ZF\DoctrineQueryBuilder`)
- [x] composer scripts
- [x] short array notation everywhere
- [x] set minimum supported PHP version to 5.6
- [x] Update `ZF\Doctrine\QueryBuilder\Module`:
  - ~~Remove direct interface implementations (these will be phased out of ModuleManager and pushed to the appropriate components in the near future)~~ it is not clear if these interfaces will be phased out
  - [x] Remove getAutoloaderConfig() implementation
- [x] use `::class` notation everywhere
- [x] convert all invokables to aliases+factories
- [x] update `composer.json` to tagged latest version of dependencies
- [x] add `phpcs.xml` rules to follow those in `zf-apigility` and `zf-apigility-admin`, and run across code base
- [x] added new factories
  - [x] `Query\Provider\DefaultOdmFactory`
  - [x] `Query\Provider\DefaultOrmFactory`
- [x] added tests for classes:
  - [x] `Query\Provider\DefaultOdm`
  - [x] `Query\Provider\DefaultOdmFactory`
  - [x] `Query\Provider\DefaultOrm`
  - [x] `Query\Provider\DefaultOrmFactory`

### CODE REVIEW

**Comment by shandyDev** [comment]
I tested latest version from your branch - it seems all works (I tested only ORM filters/order).
But I found some other issue, I created issue - https://github.com/zfcampus/zf-apigility-doctrine/issues/278

**Comment by webimpress** [comment]
@zfcampus/doctrine ready to review and tests ! :)

**Comment by webimpress** [comment]
ping @jguittard @weierophinney

**Comment by thomasvargiu** [comment]
@webimpress Can you update packagist for the 1.5.0 tag?

**Pull request closed without merging**
