### PR TITLE
[WIP] ZF3 compatibility 

### PR DESCRIPTION
**Pull request by shandyDev**
Hi guys!
I'm starting this pull request to end progress on https://github.com/zfcampus/zf-apigility/issues/167
It depends on https://github.com/zfcampus/zf-apigility-doctrine/pull/267 and this still not done yet.

Also still need edit travis configuration to test lowest and latest dependency (it should works on both ZF v2 & v3).

### CODE REVIEW

**Comment by webimpress** [comment]
@shandyDev [`zf-apigility-doctrine` 2.1.0](https://github.com/zfcampus/zf-apigility-doctrine/releases/tag/2.1.0) has been released now. Are you going to continue with your PR or shall I take it over?

**Comment by shandyDev** [comment]
@webimpress Thanks!
Yes, I will install apigility skeleton with new 2.1.0 and will test my code with it and give you know results.

**Comment by webimpress** [comment]
@shandyDev Thanks for your effort, I'm just working on this repository, you can track progress in #32. I've used your commits and preparing everything to be released shortly. Thanks!

**Comment by shandyDev** [comment]
I close this pull request, continued in rebased pull - https://github.com/zfcampus/zf-doctrine-querybuilder/pull/32

**Pull request closed without merging**
