### PR TITLE
Fixed typo in namespace

### PR DESCRIPTION
**Pull request by jguittard**

### CODE REVIEW

**Comment by kusmierz** [comment]
@TomHAnderson could you merge it, please?

**Comment by dorongutman** [comment]
@TomHAnderson these typos are making it hard to use this repo. if you could merge this PR that would be awesome

**Comment by renooo** [comment]
@dorongutman

You can use this branch :
https://github.com/zfcampus/zf-doctrine-querybuilder/tree/develop

The problem has been solved here :
https://github.com/zfcampus/zf-doctrine-querybuilder/pull/7

**Comment by TomHAnderson** [comment]
Fixed in https://github.com/zfcampus/zf-doctrine-querybuilder/releases/tag/0.1.2

**Pull request merged**
